// ============================================================
//  CommonBlockExtractor.h / .cpp
//
//  Walks the Flang parse tree (Fortran::parser::Program) for a
//  single translation unit and populates a list of
//  CommonBlockDecl objects.
//
//  Flang parse tree quick-reference
//  ─────────────────────────────────────────────────────────
//  The Flang "parse tree" is a hierarchy of C++ variant/tuple
//  types generated by flang/lib/Parser/parse-tree.h.
//
//  Key node types we care about:
//
//    CommonStmt          – COMMON /name/ var, var, ...
//    TypeDeclarationStmt – REAL X(100), Y
//    EquivalenceStmt     – EQUIVALENCE (X,Y)
//    SaveStmt            – SAVE /blockname/
//
//  Traversal is done with Fortran::parser::Walk(), which takes
//  a visitor with Pre()/Post() overloads for each node type.
// ============================================================
#pragma once

// Flang headers (available when built against LLVM/Flang install)
// In a real build these come from the Flang CMake export targets.
#include "flang/Parser/parse-tree.h"
#include "flang/Parser/parse-tree-visitor.h"
#include "flang/Parser/parsing.h"
#include "flang/Semantics/semantics.h"
#include "flang/Semantics/symbol.h"

#include "CommonBlockDB.h"
#include <string>
#include <vector>

namespace CommonAnalyzer {

// ────────────────────────────────────────────────────────────
//  ExtractorVisitor
//  Passed to Fortran::parser::Walk().  Pre() returns true to
//  descend into children; Post() fires on the way back up.
// ────────────────────────────────────────────────────────────
class ExtractorVisitor {
public:
    explicit ExtractorVisitor(
        const std::string& filename,
        const Fortran::semantics::SemanticsContext& semCtx)
        : filename_(filename), semCtx_(semCtx) {}

    // ── COMMON statement ─────────────────────────────────────
    //
    //  Grammar:
    //    COMMON [/[block-name]/] common-block-object-list
    //           [[,] /[block-name]/  common-block-object-list]…
    //
    //  In the parse tree this appears as:
    //    CommonStmt { std::list<CommonBlockObject> objects; }
    //  where each CommonBlockObject has an optional name and a
    //  list of CommonBlockObjectName items.
    //
    bool Pre(const Fortran::parser::CommonStmt& stmt) {
        // Each "block" within the statement (a COMMON statement
        // can declare multiple blocks separated by /…/)
        for (auto& block : stmt.v) {
            CommonBlockDecl decl;
            decl.loc.filename = filename_;

            // block.t is a tuple<optional<Name>, list<Name>>
            const auto& nameOpt = std::get<0>(block.t);
            decl.blockName = nameOpt
                ? std::string{nameOpt->ToString()}
                : "";   // blank COMMON

            // Extract each variable listed in this block
            for (auto& obj : std::get<1>(block.t)) {
                VarDecl var;
                var.name = obj.name.ToString();
                var.loc.filename = filename_;

                // Look up the symbol in the semantic context to
                // get the resolved type information
                fillTypeFromSymbol(var, obj.name.ToString());

                decl.vars.push_back(std::move(var));
            }

            decl.totalBytes = decl.computeTotalBytes();
            currentDecls_.push_back(std::move(decl));
        }
        return true;
    }

    // ── EQUIVALENCE statement ─────────────────────────────────
    //  EQUIVALENCE (A, B), (C(1), D(2))
    //  Stored so the checker can detect storage aliasing.
    bool Pre(const Fortran::parser::EquivalenceStmt& stmt) {
        // Each equivalence set is a list of designators
        for (auto& set : stmt.v) {
            if (set.size() < 2) continue;
            EquivRelation eq;
            eq.loc.filename = filename_;
            // Simple case: first two items in the set
            eq.var1 = designatorName(set[0]);
            eq.var2 = designatorName(set[1]);
            pendingEquivs_.push_back(eq);
        }
        return true;
    }

    // ── SAVE statement ────────────────────────────────────────
    //  SAVE /blockname/ marks the block with the SAVE attribute.
    //  Inconsistent SAVE usage across TUs is undefined behavior.
    bool Pre(const Fortran::parser::SaveStmt& stmt) {
        for (auto& item : stmt.v) {
            if (const auto* name = std::get_if<
                    Fortran::parser::CommonBlockObject>(&item)) {
                savedBlocks_.insert(name->name.ToString());
            }
        }
        return true;
    }

    // ── Type declaration statements ───────────────────────────
    //  REAL X(100)
    //  We capture these so that when we later see X in COMMON we
    //  can resolve its type without relying solely on semantics.
    bool Pre(const Fortran::parser::TypeDeclarationStmt& stmt) {
        // stmt.t = tuple<DeclarationTypeSpec, list<AttrSpec>,
        //                list<EntityDecl>>
        FortranType ftype = typeSpecToEnum(std::get<0>(stmt.t));
        for (auto& entity : std::get<2>(stmt.t)) {
            const auto& entityName = entity.name.ToString();
            typeCache_[entityName] = ftype;
            dimCache_[entityName]  = extractDims(entity);
        }
        return true;
    }

    // Default: descend into everything else
    template<typename T>
    bool Pre(const T&) { return true; }
    template<typename T>
    void Post(const T&) {}

    // ── Finalisation ──────────────────────────────────────────
    //  Called after Walk() completes.  Attaches EQUIVALENCE and
    //  SAVE information to the relevant CommonBlockDecl objects.
    std::vector<CommonBlockDecl> finalize() {
        // Attach SAVE attribute
        for (auto& decl : currentDecls_) {
            if (savedBlocks_.count(decl.blockName))
                decl.hasSaveAttr = true;
        }
        // Attach EQUIVALENCE (simple: attach to last decl for now)
        if (!currentDecls_.empty()) {
            currentDecls_.back().equivs = pendingEquivs_;
        }
        return currentDecls_;
    }

private:
    const std::string& filename_;
    const Fortran::semantics::SemanticsContext& semCtx_;

    std::vector<CommonBlockDecl> currentDecls_;
    std::vector<EquivRelation>   pendingEquivs_;
    std::set<std::string>        savedBlocks_;
    std::map<std::string, FortranType>    typeCache_;
    std::map<std::string, std::vector<int>> dimCache_;

    // ── Helpers ───────────────────────────────────────────────

    // Resolve a variable's type by first checking the semantic
    // symbol table, then falling back to our typeCache_.
    void fillTypeFromSymbol(VarDecl& var, const std::string& name) {
        // Look up the semantic symbol
        const Fortran::semantics::Symbol* sym =
            semCtx_.FindSymbol(name);

        if (sym) {
            const auto& typeExpr = sym->GetType();
            if (typeExpr) {
                var.type = categoryToEnum(typeExpr->category());
                // For character, extract length
                if (var.type == FortranType::CHARACTER) {
                    var.charLen = extractCharLen(*typeExpr);
                }
            }
            // Extract array dimensions from shape
            if (sym->IsObjectArray()) {
                var.isArray = true;
                for (auto& dim : sym->GetShape()) {
                    if (dim.ubound().IsConstant())
                        var.dims.push_back(dim.ubound().GetValue());
                }
            }
        } else {
            // Fall back to explicit type declaration cache
            if (typeCache_.count(name)) {
                var.type    = typeCache_.at(name);
                if (dimCache_.count(name)) {
                    var.dims    = dimCache_.at(name);
                    var.isArray = !var.dims.empty();
                }
            } else {
                // Implicit typing: I–N → INTEGER, else REAL
                char first = std::toupper(name.empty() ? 'A' : name[0]);
                var.type = (first >= 'I' && first <= 'N')
                               ? FortranType::INTEGER
                               : FortranType::REAL;
            }
        }
    }

    // Map Flang TypeCategory → our FortranType enum
    FortranType categoryToEnum(
        Fortran::common::TypeCategory cat) const
    {
        using TC = Fortran::common::TypeCategory;
        switch (cat) {
            case TC::Integer:   return FortranType::INTEGER;
            case TC::Real:      return FortranType::REAL;
            case TC::Complex:   return FortranType::COMPLEX;
            case TC::Logical:   return FortranType::LOGICAL;
            case TC::Character: return FortranType::CHARACTER;
            default:            return FortranType::UNKNOWN;
        }
    }

    // Map parse-tree DeclarationTypeSpec → FortranType
    FortranType typeSpecToEnum(
        const Fortran::parser::DeclarationTypeSpec& spec) const
    {
        // spec is a variant; visit the IntrinsicTypeSpec arm
        return std::visit([](auto& inner) -> FortranType {
            using T = std::decay_t<decltype(inner)>;
            if constexpr (std::is_same_v<T,
                    Fortran::parser::IntrinsicTypeSpec>) {
                return intrinsicToEnum(inner);
            }
            return FortranType::UNKNOWN;
        }, spec.u);
    }

    static FortranType intrinsicToEnum(
        const Fortran::parser::IntrinsicTypeSpec& spec)
    {
        return std::visit([](auto& inner) -> FortranType {
            using T = std::decay_t<decltype(inner)>;
            if constexpr (std::is_same_v<T,
                    Fortran::parser::IntrinsicTypeSpec::Real>)
                return FortranType::REAL;
            if constexpr (std::is_same_v<T,
                    Fortran::parser::IntrinsicTypeSpec::DoublePrecision>)
                return FortranType::DOUBLE_PRECISION;
            if constexpr (std::is_same_v<T,
                    Fortran::parser::IntrinsicTypeSpec::Integer>)
                return FortranType::INTEGER;
            if constexpr (std::is_same_v<T,
                    Fortran::parser::IntrinsicTypeSpec::Complex>)
                return FortranType::COMPLEX;
            if constexpr (std::is_same_v<T,
                    Fortran::parser::IntrinsicTypeSpec::Logical>)
                return FortranType::LOGICAL;
            if constexpr (std::is_same_v<T,
                    Fortran::parser::IntrinsicTypeSpec::Character>)
                return FortranType::CHARACTER;
            return FortranType::UNKNOWN;
        }, spec.u);
    }

    // Extract CHARACTER*N length from a type expression
    int extractCharLen(
        const Fortran::semantics::DeclTypeSpec& typeExpr) const
    {
        if (auto* charType = typeExpr.AsCharacter()) {
            if (charType->length().isExplicit()) {
                auto& lenParam = charType->length().GetExplicitLength();
                if (lenParam.IsConstant())
                    return static_cast<int>(lenParam.GetValue());
            }
        }
        return 1;
    }

    // Extract compile-time constant dimensions from EntityDecl
    std::vector<int> extractDims(
        const Fortran::parser::EntityDecl& entity) const
    {
        std::vector<int> dims;
        if (entity.arraySpec) {
            for (auto& spec : entity.arraySpec->v) {
                if (auto* explicit_ =
                        std::get_if<
                            Fortran::parser::ExplicitShapeSpec>(&spec)) {
                    // upper bound; lower bound defaults to 1
                    if (auto val = evalConstExpr(explicit_->upper))
                        dims.push_back(*val);
                }
            }
        }
        return dims;
    }

    std::optional<int> evalConstExpr(
        const Fortran::parser::ScalarIntConstantExpr& expr) const
    {
        // For compile-time integer literals this is straightforward
        if (auto* literal =
                std::get_if<Fortran::parser::LiteralConstant>(
                    &expr.thing.thing.thing.u)) {
            if (auto* intLit =
                    std::get_if<Fortran::parser::IntLiteralConstant>(
                        &literal->u)) {
                return std::stoi(std::string{intLit->t.str()});
            }
        }
        return std::nullopt;
    }

    std::string designatorName(
        const Fortran::parser::Designator& d) const
    {
        if (auto* name = std::get_if<Fortran::parser::Name>(&d.u))
            return name->ToString();
        return "<complex-designator>";
    }
};

// ────────────────────────────────────────────────────────────
//  Top-level driver: parse one file and return its decls
// ────────────────────────────────────────────────────────────
std::vector<CommonBlockDecl> extractFromFile(
    const std::string& filename,
    const Fortran::parser::CookedSource& cooked,
    const Fortran::parser::Program& parseTree,
    const Fortran::semantics::SemanticsContext& semCtx);

} // namespace CommonAnalyzer
