// ============================================================
//  Reporter.h / Reporter.cpp
//
//  Formats and prints Diagnostic objects.
//  Also writes the migration advisor output.
// ============================================================
#pragma once

#include "CommonBlockDB.h"
#include <vector>
#include <ostream>
#include <fstream>

namespace CommonAnalyzer {

// ────────────────────────────────────────────────────────────
//  Diagnostic::print() — structured error output
//
//  Format:
//  [ERROR]   COMMON /DATA/
//    File1.f:10  REAL X(100)  → 400 bytes
//    File2.f:5   INTEGER I(200) → 800 bytes
//    Issue: Size mismatch
//
//  [WARNING] COMMON /BLK/
//    File3.f:22  REAL X : not aligned to 8 bytes at offset 4
// ────────────────────────────────────────────────────────────
inline void Diagnostic::print() const {
    std::ostream& out = std::cerr;

    // Severity badge
    switch (severity) {
        case Severity::ERROR:   out << "[ERROR]   "; break;
        case Severity::WARNING: out << "[WARNING] "; break;
        case Severity::NOTE:    out << "[NOTE]    "; break;
    }

    // Block name
    out << "COMMON /" << (blockName.empty() ? "(blank)" : blockName) << "/\n";

    // Multi-line message (indented)
    for (auto& ch : message) {
        if (ch == '\n') out << "\n  ";
        else out << ch;
    }
    out << "\n";

    // Migration hint (optional, guarded by env var or flag)
    static bool showHints =
        (std::getenv("COMMON_ANALYZER_HINTS") != nullptr);
    if (showHints && !migrationHint.empty()) {
        out << "\n  ── Migration hint ──────────────────────\n";
        for (auto& ch : migrationHint) {
            out << ch;
        }
        out << "\n  ────────────────────────────────────────\n";
    }

    out << "\n";
}

// ────────────────────────────────────────────────────────────
//  Full diagnostic report
// ────────────────────────────────────────────────────────────
inline void printReport(
    const std::vector<Diagnostic>& diags,
    std::ostream& out = std::cerr)
{
    int errors   = 0;
    int warnings = 0;

    out << "╔══════════════════════════════════════════════════════╗\n";
    out << "║  Fortran COMMON Block Memory Safety Analyzer         ║\n";
    out << "╚══════════════════════════════════════════════════════╝\n\n";

    for (const auto& d : diags) {
        d.print();
        if (d.severity == Severity::ERROR)   ++errors;
        if (d.severity == Severity::WARNING) ++warnings;
    }

    out << "── Summary ──────────────────────────────────────────\n";
    out << "  " << errors   << " error(s),  "
                << warnings << " warning(s) found\n\n";

    if (errors > 0) {
        out << "  RESULT: UNSAFE — memory safety violations detected\n\n";
    } else if (warnings > 0) {
        out << "  RESULT: SUSPICIOUS — potential issues detected\n\n";
    } else {
        out << "  RESULT: PASS — no violations found\n\n";
    }
}

// ────────────────────────────────────────────────────────────
//  Migration advisor: write a complete MODULE per COMMON block
// ────────────────────────────────────────────────────────────
inline void writeMigrationReport(
    const GlobalCommonDB& db,
    std::ostream& out)
{
    out << "! ============================================================\n";
    out << "! COMMON → MODULE Migration Advisor\n";
    out << "! Auto-generated by Fortran COMMON Block Memory Safety Analyzer\n";
    out << "! ============================================================\n\n";

    for (const auto& [blockName, decls] : db.blocks) {
        if (decls.empty()) continue;
        const auto& canonical = decls[0]; // use first TU as reference

        std::string modName =
            blockName.empty() ? "BlankCommon" : blockName;
        // Capitalise
        if (!modName.empty()) modName[0] = std::toupper(modName[0]);
        modName += "Mod";

        out << "! ── Block: /" << (blockName.empty()?"(blank)":blockName)
            << "/ ──────────────────────────────\n";
        out << "MODULE " << modName << "\n";
        out << "  IMPLICIT NONE\n";
        out << "  SAVE  ! Fortran MODULEs are SAVE by default\n\n";

        for (const auto& v : canonical.vars) {
            out << "  " << v.typeStr();
            if (v.isArray) {
                out << ", DIMENSION(";
                for (size_t i = 0; i < v.dims.size(); ++i) {
                    if (i) out << ",";
                    out << v.dims[i];
                }
                out << ")";
            }
            out << " :: " << v.name << "\n";
        }

        out << "\nEND MODULE " << modName << "\n\n";

        // Show how to replace COMMON in a sample subroutine
        out << "! Usage in subroutines (replace COMMON declaration with):\n";
        out << "!   USE " << modName << "\n";
        out << "!   (Remove the COMMON statement entirely)\n\n";

        // If there were inconsistencies, note them
        if (decls.size() > 1) {
            out << "! NOTE: This block was declared in "
                << decls.size() << " files:\n";
            for (const auto& d : decls) {
                out << "!   " << d.loc.str()
                    << "  (" << d.totalBytes << " bytes)\n";
            }
            out << "! Resolve any size/type mismatches before using this MODULE.\n";
        }
        out << "\n";
    }
}

} // namespace CommonAnalyzer
